### ISSUE TITLE
Omni results dissapear

### ISSUE THREAD

**Issue by bbtdev** [yami-beta/asyncomplete-omni.vim#9]
So I have multiple sources, the omni results only appear the first time, if I type another letter the omni results dissapear and only the results from other sources show up: tags etc. I tried playing with priority, no affect.

If omni are the only source, it works correctly!

config:
```
"TESTING
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
Plug 'prabirshrestha/asyncomplete-tags.vim'
Plug 'yami-beta/asyncomplete-omni.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'
Plug 'prabirshrestha/asyncomplete-necovim.vim'
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#tags#get_source_options({
    \ 'name': 'tags',
    \ 'whitelist': ['ruby'],
    \ 'priority': '9',
    \ 'completor': function('asyncomplete#sources#tags#completor'),
    \ 'config': {
    \    'max_file_size': -1,
    \  },
    \ }))

call asyncomplete#register_source(asyncomplete#sources#omni#get_source_options({
    \ 'name': 'omni',
    \ 'whitelist': ['*'],
    \ 'priority': '10',
    \ 'blacklist': ['html'],
    \ 'completor': function('asyncomplete#sources#omni#completor')
    \  }))

```

**Comment by prabirshrestha** [comment]
@bbtdev can you try these three options? I had made some changes in asyncomplete.vim so want to make sure if the bug is in omni source or in asyncomplete.vim

1. revert https://github.com/prabirshrestha/asyncomplete.vim/commit/720be509c8b36de6e036a6b126f335203342c906and see if it works.
2. try https://github.com/prabirshrestha/asyncomplete.vim/commit/aa3ad0d69ae4853d79ea3d677103ab87d08d9341 an see if it works.
3. try https://github.com/prabirshrestha/asyncomplete.vim/tree/v1.0 and see if it works.

**Comment by bbtdev** [comment]
I have no time to test this, Im sorry
